"""HTML report generation for Revibe."""

from datetime import datetime
from html import escape
from typing import List, Optional

from revibe import __version__
from revibe.fixer import FixPlan, generate_fix_plan
from revibe.metrics import CodebaseMetrics
from revibe.smells import get_smell_descriptions


def generate_html_report(
    metrics: CodebaseMetrics,
    codebase_path: str,
    fix_plan: Optional[FixPlan] = None,
) -> str:
    """
    Generate a self-contained HTML report.

    Args:
        metrics: Codebase metrics
        codebase_path: Path to the scanned codebase
        fix_plan: Optional pre-generated fix plan

    Returns:
        Complete HTML document as string
    """
    if fix_plan is None:
        fix_plan = generate_fix_plan(codebase_path, metrics)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Generate sections
    health_section = _generate_health_section(metrics)
    metrics_section = _generate_metrics_section(metrics)
    fixes_section = _generate_fixes_section(fix_plan)
    smells_section = _generate_smells_section(metrics)
    languages_section = _generate_languages_section(metrics)
    duplicates_section = _generate_duplicates_section(metrics)

    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Revibe Report — {escape(codebase_path)}</title>
    <style>
{_get_styles()}
    </style>
</head>
<body>
    <header>
        <div class="container">
            <div class="header-content">
                <h1>🔍 Revibe Report</h1>
                <div class="meta">
                    <span class="path">{escape(codebase_path)}</span>
                    <span class="version">v{__version__}</span>
                    <span class="date">{timestamp}</span>
                </div>
            </div>
        </div>
    </header>

    <main class="container">
        {health_section}
        {fixes_section}
        {metrics_section}
        {smells_section}
        {languages_section}
        {duplicates_section}
    </main>

    <footer>
        <div class="container">
            <p>Generated by <a href="https://revibe.help">Revibe</a> v{__version__}</p>
            <p class="tip">Run <code>revibe scan . --fix</code> to generate copy-paste fix instructions</p>
        </div>
    </footer>

    <script>
{_get_scripts()}
    </script>
</body>
</html>'''

    return html


def _get_styles() -> str:
    """Get CSS styles for the report."""
    return '''
:root {
    --bg-primary: #0f172a;
    --bg-secondary: #1e293b;
    --bg-tertiary: #334155;
    --text-primary: #f1f5f9;
    --text-secondary: #94a3b8;
    --text-muted: #64748b;
    --accent: #38bdf8;
    --accent-hover: #0ea5e9;
    --success: #22c55e;
    --warning: #eab308;
    --danger: #ef4444;
    --elevated: #f97316;
    --border: #475569;
    --code-bg: #1e293b;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: var(--bg-primary);
    color: var(--text-primary);
    line-height: 1.6;
    min-height: 100vh;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1.5rem;
}

header {
    background: var(--bg-secondary);
    border-bottom: 1px solid var(--border);
    padding: 1.5rem 0;
    position: sticky;
    top: 0;
    z-index: 100;
}

.header-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 1rem;
}

header h1 {
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--accent);
}

.meta {
    display: flex;
    gap: 1.5rem;
    flex-wrap: wrap;
    color: var(--text-secondary);
    font-size: 0.9rem;
}

.meta .path {
    font-family: monospace;
    background: var(--bg-tertiary);
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
}

main {
    padding: 2rem 0;
}

.section {
    margin-bottom: 2.5rem;
}

.section-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 1rem;
    color: var(--text-primary);
    display: flex;
    align-items: center;
    gap: 0.5rem;
}

.card {
    background: var(--bg-secondary);
    border-radius: 12px;
    padding: 1.5rem;
    border: 1px solid var(--border);
}

.health-card {
    display: flex;
    align-items: center;
    gap: 2rem;
    flex-wrap: wrap;
}

.score-circle {
    width: 140px;
    height: 140px;
    border-radius: 50%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: 2.5rem;
    font-weight: 700;
    position: relative;
    flex-shrink: 0;
}

.score-circle::before {
    content: "";
    position: absolute;
    inset: 4px;
    border-radius: 50%;
    background: var(--bg-secondary);
}

.score-circle span {
    position: relative;
    z-index: 1;
}

.score-circle .label {
    font-size: 0.8rem;
    font-weight: 400;
    color: var(--text-secondary);
}

.score-low { background: conic-gradient(var(--success) calc(var(--score) * 3.6deg), var(--bg-tertiary) 0); }
.score-moderate { background: conic-gradient(var(--warning) calc(var(--score) * 3.6deg), var(--bg-tertiary) 0); }
.score-elevated { background: conic-gradient(var(--elevated) calc(var(--score) * 3.6deg), var(--bg-tertiary) 0); }
.score-high, .score-critical { background: conic-gradient(var(--danger) calc(var(--score) * 3.6deg), var(--bg-tertiary) 0); }

.health-details {
    flex: 1;
    min-width: 250px;
}

.risk-badge {
    display: inline-block;
    padding: 0.25rem 0.75rem;
    border-radius: 20px;
    font-size: 0.85rem;
    font-weight: 600;
    text-transform: uppercase;
    margin-bottom: 1rem;
}

.risk-low { background: var(--success); color: #000; }
.risk-moderate { background: var(--warning); color: #000; }
.risk-elevated { background: var(--elevated); color: #fff; }
.risk-high, .risk-critical { background: var(--danger); color: #fff; }

.metrics-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
}

.metric-card {
    background: var(--bg-tertiary);
    padding: 1rem;
    border-radius: 8px;
}

.metric-value {
    font-size: 1.75rem;
    font-weight: 700;
    color: var(--accent);
}

.metric-label {
    font-size: 0.85rem;
    color: var(--text-secondary);
    margin-top: 0.25rem;
}

.metric-detail {
    font-size: 0.8rem;
    color: var(--text-muted);
}

.fix-item {
    background: var(--bg-tertiary);
    border-radius: 8px;
    margin-bottom: 1rem;
    overflow: hidden;
}

.fix-header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem;
    cursor: pointer;
    user-select: none;
}

.fix-header:hover {
    background: var(--bg-secondary);
}

.fix-priority {
    padding: 0.2rem 0.5rem;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
}

.priority-critical { background: var(--danger); }
.priority-high { background: var(--elevated); }
.priority-medium { background: var(--warning); color: #000; }
.priority-low { background: var(--success); color: #000; }

.fix-title {
    flex: 1;
    font-weight: 500;
}

.fix-toggle {
    color: var(--text-muted);
    transition: transform 0.2s;
}

.fix-item.open .fix-toggle {
    transform: rotate(180deg);
}

.fix-content {
    display: none;
    padding: 0 1rem 1rem;
}

.fix-item.open .fix-content {
    display: block;
}

.fix-description {
    color: var(--text-secondary);
    margin-bottom: 1rem;
    font-size: 0.95rem;
}

.fix-prompt {
    background: var(--code-bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem;
    font-family: "SF Mono", Monaco, "Cascadia Code", monospace;
    font-size: 0.85rem;
    line-height: 1.5;
    white-space: pre-wrap;
    overflow-x: auto;
    position: relative;
}

.copy-btn {
    position: absolute;
    top: 0.5rem;
    right: 0.5rem;
    background: var(--accent);
    color: var(--bg-primary);
    border: none;
    padding: 0.4rem 0.75rem;
    border-radius: 4px;
    font-size: 0.8rem;
    font-weight: 500;
    cursor: pointer;
    transition: background 0.2s;
}

.copy-btn:hover {
    background: var(--accent-hover);
}

.copy-btn.copied {
    background: var(--success);
}

.smell-bar {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 0.75rem;
}

.smell-name {
    width: 180px;
    font-size: 0.9rem;
    color: var(--text-secondary);
}

.smell-track {
    flex: 1;
    height: 8px;
    background: var(--bg-tertiary);
    border-radius: 4px;
    overflow: hidden;
}

.smell-fill {
    height: 100%;
    border-radius: 4px;
    transition: width 0.5s ease;
}

.smell-score {
    width: 45px;
    text-align: right;
    font-size: 0.85rem;
    color: var(--text-muted);
}

.lang-bar {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 0.5rem;
}

.lang-name {
    width: 100px;
    font-size: 0.9rem;
}

.lang-track {
    flex: 1;
    height: 20px;
    background: var(--bg-tertiary);
    border-radius: 4px;
    overflow: hidden;
}

.lang-fill {
    height: 100%;
    background: var(--accent);
    border-radius: 4px;
}

.lang-value {
    width: 80px;
    text-align: right;
    font-size: 0.85rem;
    color: var(--text-secondary);
}

.duplicates-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
}

.duplicate-group {
    background: var(--bg-tertiary);
    border-radius: 8px;
    padding: 1rem;
}

.duplicate-type {
    font-size: 0.8rem;
    color: var(--text-muted);
    margin-bottom: 0.5rem;
}

.duplicate-files {
    font-family: monospace;
    font-size: 0.85rem;
}

.duplicate-files li {
    list-style: none;
    padding: 0.25rem 0;
}

footer {
    background: var(--bg-secondary);
    border-top: 1px solid var(--border);
    padding: 2rem 0;
    text-align: center;
    color: var(--text-secondary);
    font-size: 0.9rem;
}

footer a {
    color: var(--accent);
    text-decoration: none;
}

footer code {
    background: var(--bg-tertiary);
    padding: 0.2rem 0.5rem;
    border-radius: 4px;
    font-size: 0.85rem;
}

.tip {
    margin-top: 0.5rem;
    color: var(--text-muted);
}

@media print {
    :root {
        --bg-primary: #fff;
        --bg-secondary: #f8fafc;
        --bg-tertiary: #e2e8f0;
        --text-primary: #0f172a;
        --text-secondary: #475569;
        --border: #cbd5e1;
    }

    header { position: static; }
    .copy-btn { display: none; }
}

@media (max-width: 600px) {
    .health-card { flex-direction: column; text-align: center; }
    .metrics-grid { grid-template-columns: 1fr; }
}
'''


def _get_scripts() -> str:
    """Get JavaScript for the report."""
    return '''
// Toggle fix items
document.querySelectorAll('.fix-header').forEach(header => {
    header.addEventListener('click', () => {
        header.closest('.fix-item').classList.toggle('open');
    });
});

// Copy to clipboard
document.querySelectorAll('.copy-btn').forEach(btn => {
    btn.addEventListener('click', async (e) => {
        e.stopPropagation();
        const prompt = btn.closest('.fix-prompt').querySelector('code').textContent;
        await navigator.clipboard.writeText(prompt);
        btn.textContent = 'Copied!';
        btn.classList.add('copied');
        setTimeout(() => {
            btn.textContent = 'Copy';
            btn.classList.remove('copied');
        }, 2000);
    });
});
'''


def _generate_health_section(metrics: CodebaseMetrics) -> str:
    """Generate health score section."""
    risk_class = metrics.risk_level.lower()
    return f'''
        <section class="section">
            <div class="card health-card">
                <div class="score-circle score-{risk_class}" style="--score: {metrics.health_score}">
                    <span>{metrics.health_score}</span>
                    <span class="label">/ 100</span>
                </div>
                <div class="health-details">
                    <span class="risk-badge risk-{risk_class}">{metrics.risk_level} Risk</span>
                    <p>
                        {metrics.source_loc:,} lines of source code across {metrics.source_files} files.
                        {metrics.test_loc:,} lines of tests ({metrics.test_to_code_ratio * 100:.1f}% coverage).
                        Estimated ~{metrics.estimated_defects} defects based on industry research.
                    </p>
                </div>
            </div>
        </section>
'''


def _generate_metrics_section(metrics: CodebaseMetrics) -> str:
    """Generate metrics grid section."""
    test_ratio_pct = metrics.test_to_code_ratio * 100
    test_target = "✅ Good" if test_ratio_pct >= 80 else "⚠️ Low" if test_ratio_pct >= 50 else "🔴 Critical"

    return f'''
        <section class="section">
            <h2 class="section-title">📊 Metrics</h2>
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">{metrics.source_loc:,}</div>
                    <div class="metric-label">Lines of Code</div>
                    <div class="metric-detail">{metrics.source_files} source files</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{test_ratio_pct:.1f}%</div>
                    <div class="metric-label">Test Coverage {test_target}</div>
                    <div class="metric-detail">{metrics.test_loc:,} test lines / {metrics.test_files} files</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">~{metrics.estimated_defects}</div>
                    <div class="metric-label">Estimated Defects</div>
                    <div class="metric-detail">{metrics.defect_density_estimate:.1f} per KLOC</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{metrics.feature_count}</div>
                    <div class="metric-label">Features Detected</div>
                    <div class="metric-detail">{metrics.feature_interactions:,} interaction paths</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{metrics.total_functions}</div>
                    <div class="metric-label">Functions</div>
                    <div class="metric-detail">{metrics.total_classes} classes</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{len(metrics.todos)}</div>
                    <div class="metric-label">TODO/FIXME Markers</div>
                    <div class="metric-detail">Across all files</div>
                </div>
            </div>
        </section>
'''


def _generate_fixes_section(fix_plan: FixPlan) -> str:
    """Generate fixes section with copy-paste prompts."""
    if not fix_plan.fixes:
        return '''
        <section class="section">
            <h2 class="section-title">✅ No Critical Fixes Needed</h2>
            <div class="card">
                <p>Your codebase looks healthy! Keep up the good work.</p>
            </div>
        </section>
'''

    fix_items = []
    for fix in fix_plan.fixes:
        priority_class = fix.priority.lower()
        prompt_escaped = escape(fix.prompt)
        desc_escaped = escape(fix.description)

        fix_items.append(f'''
                <div class="fix-item">
                    <div class="fix-header">
                        <span class="fix-priority priority-{priority_class}">{fix.priority}</span>
                        <span class="fix-title">{escape(fix.title)}</span>
                        <span class="fix-toggle">▼</span>
                    </div>
                    <div class="fix-content">
                        <p class="fix-description">{desc_escaped}</p>
                        <div class="fix-prompt">
                            <button class="copy-btn">Copy</button>
                            <code>{prompt_escaped}</code>
                        </div>
                    </div>
                </div>
''')

    return f'''
        <section class="section">
            <h2 class="section-title">🔧 Fix Instructions</h2>
            <p style="color: var(--text-secondary); margin-bottom: 1rem;">
                Click to expand, then copy the prompt into Cursor, Claude, or your AI coding tool.
            </p>
            <div class="fixes-list">
                {"".join(fix_items)}
            </div>
        </section>
'''


def _generate_smells_section(metrics: CodebaseMetrics) -> str:
    """Generate AI smells visualization section."""
    if not metrics.ai_smell_scores:
        return ""

    descriptions = get_smell_descriptions()
    smell_bars = []

    for name, score in sorted(metrics.ai_smell_scores.items(), key=lambda x: -x[1]):
        pct = score * 100
        color = "var(--success)" if score < 0.3 else "var(--warning)" if score < 0.6 else "var(--danger)"
        desc = descriptions.get(name, name)

        smell_bars.append(f'''
                <div class="smell-bar" title="{escape(desc)}">
                    <span class="smell-name">{name.replace("_", " ").title()}</span>
                    <div class="smell-track">
                        <div class="smell-fill" style="width: {pct}%; background: {color}"></div>
                    </div>
                    <span class="smell-score">{pct:.0f}%</span>
                </div>
''')

    return f'''
        <section class="section">
            <h2 class="section-title">🤖 AI Code Smells</h2>
            <div class="card">
                {"".join(smell_bars)}
            </div>
        </section>
'''


def _generate_languages_section(metrics: CodebaseMetrics) -> str:
    """Generate language breakdown section."""
    if not metrics.languages:
        return ""

    # Sort by line count
    sorted_langs = sorted(
        metrics.languages.items(),
        key=lambda x: x[1].get("lines", 0),
        reverse=True
    )

    total_lines = sum(data.get("lines", 0) for _, data in sorted_langs)
    if total_lines == 0:
        return ""

    lang_bars = []
    for lang, data in sorted_langs[:10]:
        lines = data.get("lines", 0)
        pct = (lines / total_lines) * 100 if total_lines > 0 else 0

        lang_bars.append(f'''
                <div class="lang-bar">
                    <span class="lang-name">{escape(lang)}</span>
                    <div class="lang-track">
                        <div class="lang-fill" style="width: {pct}%"></div>
                    </div>
                    <span class="lang-value">{lines:,} lines</span>
                </div>
''')

    return f'''
        <section class="section">
            <h2 class="section-title">📁 Language Breakdown</h2>
            <div class="card">
                {"".join(lang_bars)}
            </div>
        </section>
'''


def _generate_duplicates_section(metrics: CodebaseMetrics) -> str:
    """Generate duplicates section."""
    if not metrics.duplicate_groups:
        return ""

    groups = []
    for group in metrics.duplicate_groups[:10]:
        dupe_type = "Exact duplicate" if group.is_exact else f"Near duplicate ({group.similarity:.0%} similar)"
        files = "\n".join(f"<li>{escape(f)}</li>" for f in group.files)

        groups.append(f'''
                <div class="duplicate-group">
                    <div class="duplicate-type">{dupe_type}</div>
                    <ul class="duplicate-files">{files}</ul>
                </div>
''')

    return f'''
        <section class="section">
            <h2 class="section-title">📋 Duplicate Files ({len(metrics.duplicate_groups)} groups)</h2>
            <div class="duplicates-list">
                {"".join(groups)}
            </div>
        </section>
'''
